USE MASTER 

DROP DATABASE HEXADB

CREATE DATABASE HEXADB

USE HEXADB

CREATE TABLE DEPT (
    DEPTNO INT PRIMARY KEY,
    DNAME VARCHAR(20) NOT NULL,
    LOC VARCHAR(20) NOT NULL
);



CREATE TABLE EMP (
    EMPNO INT PRIMARY KEY,
    ENAME VARCHAR(20) NOT NULL,
    JOB VARCHAR(20) NOT NULL,
    MGR_ID INT NULL,
    HIREDATE DATE NOT NULL,
    SAL INT CHECK (SAL > 0),
    COMM INT NULL,
    DEPTNO INT NOT NULL,
    FOREIGN KEY (DEPTNO) REFERENCES DEPT(DEPTNO),
    FOREIGN KEY (MGR_ID) REFERENCES EMP(EMPNO)
);

INSERT INTO DEPT VALUES (10, 'ACCOUNTING', 'NEW YORK');
INSERT INTO DEPT VALUES (20, 'RESEARCH', 'DALLAS');
INSERT INTO DEPT VALUES (30, 'SALES', 'CHICAGO');
INSERT INTO DEPT VALUES (40, 'OPERATIONS', 'BOSTON');



INSERT INTO EMP (EMPNO, ENAME, JOB, MGR_ID, HIREDATE, SAL, COMM, DEPTNO) VALUES
(7369, 'SMITH', 'CLERK', 7902, '1980-12-17', 800, NULL, 20),
(7499, 'ALLEN', 'SALESMAN', 7698, '1981-02-20', 1600, 300, 30),
(7521, 'WARD', 'SALESMAN', 7698, '1981-02-22', 1250, 500, 30),
(7566, 'JONES', 'MANAGER', 7839, '1981-04-02', 2975, NULL, 20),
(7654, 'MARTIN', 'SALESMAN', 7698, '1981-09-28', 1250, 1400, 30),
(7698, 'BLAKE', 'MANAGER', 7839, '1981-05-01', 2850, NULL, 30),
(7782, 'CLARK', 'MANAGER', 7839, '1981-06-09', 2450, NULL, 10),
(7788, 'SCOTT', 'ANALYST', 7566, '1987-04-19', 3000, NULL, 20),
(7844, 'TURNER', 'SALESMAN', 7698, '1981-09-08', 1500, 0, 30),
(7876, 'ADAMS', 'CLERK', 7788, '1987-05-23', 1100, NULL, 20),
(7900, 'JAMES', 'CLERK', 7698, '1981-12-03', 950, NULL, 30),
(7839, 'KING', 'PRESIDENT', NULL, '1981-11-17', 5000, NULL, 10),
(7902, 'FORD', 'ANALYST', 7566, '1981-12-03', 3000, NULL, 20),
(7934, 'MILLER', 'CLERK', 7782, '1982-01-23', 1300, NULL, 10);
 



SELECT d.DNAME, d.DEPTNO, SUM(e.SAL) AS total_salary
FROM DEPT d
LEFT JOIN EMP e ON d.DEPTNO = e.DEPTNO
WHERE d.DNAME = 'RESEARCH' 
GROUP BY d.DNAME, d.DEPTNO;



select * from emp;
select deptno,job ,sum(sal) as salary_sum from emp group by deptno,job;


SELECT ENAME, MGR_ID, COUNT(EMPNO) AS Num_Employees
FROM EMP
WHERE MGR_ID IS NOT NULL
GROUP BY ENAME, MGR_ID
HAVING COUNT(EMPNO) >= 2;


SELECT * FROM EMP WHERE ENAME LIKE 'A%';


SELECT * FROM EMP WHERE MGR_ID IS NULL;


SELECT EMPNO, ENAME, SAL FROM EMP WHERE SAL BETWEEN 1200 AND 1400;

SELECT * FROM EMP WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE DNAME = 'RESEARCH');

UPDATE EMP SET SAL = SAL * 1.10 WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE DNAME = 'RESEARCH');

SELECT * FROM EMP WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE DNAME = 'RESEARCH');

--without updating

SELECT * FROM EMP e  
JOIN DEPT d ON e.DEPTNO = d.DEPTNO  
WHERE d.DNAME = 'RESEARCH';


SELECT e.ENAME, e.SAL AS Original_Salary, (e.SAL * 1.10) AS Increased_Salary
FROM EMP e  
JOIN DEPT d ON e.DEPTNO = d.DEPTNO  
WHERE d.DNAME = 'RESEARCH';

SELECT COUNT(*) AS Num_Clerks FROM EMP WHERE JOB = 'CLERK';

SELECT JOB, COUNT(*) AS Num_Employees, AVG(SAL) AS Avg_Salary FROM EMP GROUP BY JOB;

SELECT * FROM EMP WHERE SAL = (SELECT MIN(SAL) FROM EMP)
UNION
SELECT * FROM EMP WHERE SAL = (SELECT MAX(SAL) FROM EMP);

SELECT * FROM DEPT WHERE DEPTNO NOT IN (SELECT DISTINCT DEPTNO FROM EMP);

SELECT ENAME, SAL FROM EMP WHERE JOB = 'ANALYST' AND SAL > 1200 AND DEPTNO = 20 ORDER BY ENAME ASC;


SELECT d.DNAME, d.DEPTNO, SUM(e.SAL) AS Total_Salary
FROM DEPT d
LEFT JOIN EMP e ON d.DEPTNO = e.DEPTNO
GROUP BY d.DNAME, d.DEPTNO;

SELECT ENAME, SAL FROM EMP WHERE ENAME IN ('MILLER', 'SMITH');


SELECT ENAME FROM EMP WHERE ENAME LIKE 'A%' OR ENAME LIKE 'M%';


SELECT ENAME, SAL * 12 AS Yearly_Salary FROM EMP WHERE ENAME = 'SMITH';


SELECT ENAME, SAL FROM EMP WHERE SAL NOT BETWEEN 1500 AND 2850;


SELECT e1.MGR_ID, e2.ENAME AS Manager_Name, COUNT(e1.EMPNO) AS Num_Employees
FROM EMP e1
JOIN EMP e2 ON e1.MGR_ID = e2.EMPNO
GROUP BY e1.MGR_ID, e2.ENAME
HAVING COUNT(e1.EMPNO) > 2;

SELECT m.ENAME AS Manager_Name, e.ENAME AS Employee_Name    
FROM EMP e LEFT JOIN EMP m ON e.MGR_ID = m.EMPNO
ORDER BY m.ENAME ;



